context:
  version: 0.1.0

package:
  name: htmx-lsp
  version: ${{ version }}

source:
  url: https://github.com/ThePrimeagen/htmx-lsp/archive/${{ version }}.tar.gz
  sha256: 704c8e9b8f979b2056d79a1750be8a7609c8de73b015db6de93ca3fc5de0c9cc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses

tests:
  - script:
      - htmx-lsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Language server for htmx
  homepage: https://github.com/ThePrimeagen/htmx-lsp
  repository: https://github.com/ThePrimeagen/htmx-lsp

extra:
  recipe-maintainers:
    - danielnachun
